cp case2/pointingsimulation_openhpc-compute-0.novalocal_0.jpg figures/case2.jpg
cp case3/pointingsimulation_openhpc-compute-0.novalocal_0.jpg figures/case3.jpg
cp case5/100s/pointingsimulation_openhpc-compute-0.novalocal_0.jpg figures/case5_100s.jpg
cp case5/10s/pointingsimulation_openhpc-compute-0.novalocal_0.jpg figures/case5_10s.jpg
cp case5/30s/pointingsimulation_openhpc-compute-0.novalocal_0.jpg figures/case5_30s.jpg
cp case6/0/pointingsimulation_openhpc-compute-0.novalocal_0.jpg figures/case6_0.jpg
cp case6/m75/pointingsimulation_openhpc-compute-0.novalocal_0.jpg figures/case6_m75.jpg
cp case6/p15/pointingsimulation_openhpc-compute-0.novalocal_0.jpg figures/case6_p15.jpg
cp case7/pointingsimulation_openhpc-compute-0.novalocal_0.jpg figures/case7.jpg
cp case10/delta-ra/pointingsimulation_openhpc-compute-0.novalocal_0.jpg figures/case10_delta-ra.jpg
cp case10/delta-dec/pointingsimulation_openhpc-compute-0.novalocal_0.jpg figures/case10_delta-dec.jpg

cp case3/pointing_error_precision.png figures/case3_pointing_error_precision.png
cp case5/100s/pointing_error_precision.png figures/case5_100s_pointing_error_precision.png
cp case5/10s/pointing_error_precision.png figures/case5_10s_pointing_error_precision.png
cp case5/30s/pointing_error_precision.png figures/case5_30s_pointing_error_precision.png
cp case6/0/pointing_error_precision.png figures/case6_0_pointing_error_precision.png
cp case6/p15/pointing_error_precision.png figures/case6_p15_pointing_error_precision.png
cp case6/m75/pointing_error_precision.png figures/case6_m75_pointing_error_precision.png
cp case7/pointing_error_precision.png figures/case7_pointing_error_precision.png
cp case10/delta-ra/pointing_error_precision.png figures/case10_delta-ra_pointing_error_precision.png
cp case10/delta-dec/pointing_error_precision.png figures/case10_delta-dec_pointing_error_precision.png

cp case3/azel.png figures/case3_azel.png
cp case5/100s/azel.png figures/case5_100s_azel.png
cp case5/10s/azel.png figures/case5_10s_azel.png
cp case5/30s/azel.png figures/case5_30s_azel.png
cp case6/0/azel.png figures/case6_0_azel.png
cp case6/p15/azel.png figures/case6_p15_azel.png
cp case6/m75/azel.png figures/case6_m75_azel.png
cp case7/azel.png figures/case7_azel.png
cp case10/delta-ra/azel.png figures/case10_delta-ra_azel.png
cp case10/delta-dec/azel.png figures/case10_delta-dec_azel.png
